[build]
  publish = "."
  functions = "jogos/palavro/backend/netlify/functions"

[functions]
  included_files = ["jogos/palavro/data/**"]

[[redirects]]
  from = "/jogos/termo"
  to = "/jogos/palavro/"
  status = 301

[[redirects]]
  from = "/jogos/termo/*"
  to = "/jogos/palavro/:splat"
  status = 301

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
