[build]
  publish = "."
  functions = "jogos/termo/backend/netlify/functions"

[functions]
  included_files = ["jogos/termo/data/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
